'use client'
import PrivateRoute from '@/components/PrivateRoute'
import GlobalStyle from '@/styles/globalStyles'
import { theme } from '@/styles/theme'
import { checkIsPublicRoute } from '@/utils/check-is-public-route'
import { usePathname } from 'next/navigation'
import React from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { ThemeProvider } from 'styled-components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentPathname = usePathname()

  const isPublicPage = checkIsPublicRoute(currentPathname)

  return (
    <>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <html lang="en">
          <body>
            <div>
              <ToastContainer autoClose={3000} />
              {isPublicPage && children}

              {!isPublicPage && <PrivateRoute>{children}</PrivateRoute>}
            </div>
          </body>
        </html>
      </ThemeProvider>
    </>
  )
}
